version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bajaj-r4-api:prod
    container_name: bajaj-r4-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: bajaj-r4-api:dev
    container_name: bajaj-r4-api-dev
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - /app/venv
      - /app/__pycache__
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
